### PR TITLE
update graphql-tools major

### PR DESCRIPTION
**Pull request by n1ru4l**

### CODE REVIEW

**Comment by Urigo** [comment]
@n1ru4l thank you!
After doing that (when @ardatan is back and will publish the next major), I would also love it if you could update all dependencies on this library,  merge-test https://github.com/kamilkisiela/graphql-config/pull/696 and have another review of the open issues.
And after that also create a new release.

Thank you!

**Comment by n1ru4l** [comment]
@kamilkisiela Please give me access 😄

**Comment by pieh** [comment]
@n1ru4l @kamilkisiela 

I think this bump (and publishing `graphql-config` with minor) introduced subtle breaking change:

`@graphql-tools/url-loader@^6` has`extract-files@9.0.0` dependency ( https://unpkg.com/browse/@graphql-tools/url-loader@6.10.1/package.json ) and `extract-files@9.0.0` declares following `engines.node` ( https://unpkg.com/browse/extract-files@9.0.0/package.json ):

```
"engines": {
  "node": "^10.17.0 || ^12.0.0 || >= 13.7.0"
}
```

`@graphql-tools/url-loader@^7` has `extract-files@11.0.0` dependency ( https://unpkg.com/browse/@graphql-tools/url-loader@7.0.3/package.json ) and `extract-files@11.0.0` declares following `engines.node` ( https://unpkg.com/browse/extract-files@11.0.0/package.json ):

```
"engines": {
  "node": "^12.20 || >= 14.13"
}
```

Because of this transitional dependency latest version of `graphql-config` changed valid node versions in minor release (`^10.17.0` and `>= 12.0.0 <12.20.0` are no longer valid engines). This did trips up our test setup in CIs that make use of `yarn` and now it fails installation (running on `node@12.18.3`)  - I probably can workaround that by using `--ignore-engines` yarn option or maybe pinning version of `graphql-config`, but I figured I would at least let you know about this.

**Comment by n1ru4l** [comment]
@pieh Thank you for the report! For now you can indeed pin the graphql-config version. Sorry for the inconvenience!

**Pull request merged**
